// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBF4dAoa8REnub0K-_5lKzSjmHci15ckG0',
    appId: '1:581579660522:web:d872b78ad51ca88dc4cb93',
    messagingSenderId: '581579660522',
    projectId: 'kaamsetu-1d79f',
    authDomain: 'kaamsetu-1d79f.firebaseapp.com',
    storageBucket: 'kaamsetu-1d79f.firebasestorage.app',
    measurementId: 'G-MVJ2RL1WLX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbjbRwKJ18QIS8CUpMHAkitsdn48CZNv8',
    appId: '1:581579660522:android:7b32c4770d9f3a7fc4cb93',
    messagingSenderId: '581579660522',
    projectId: 'kaamsetu-1d79f',
    storageBucket: 'kaamsetu-1d79f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAM752eRpeTGJzcel2BI2luDYrs4joF60Y',
    appId: '1:581579660522:ios:18b59df4b3d4fa05c4cb93',
    messagingSenderId: '581579660522',
    projectId: 'kaamsetu-1d79f',
    storageBucket: 'kaamsetu-1d79f.firebasestorage.app',
    iosBundleId: 'com.kaamsetu.kaamsetu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAM752eRpeTGJzcel2BI2luDYrs4joF60Y',
    appId: '1:581579660522:ios:18b59df4b3d4fa05c4cb93',
    messagingSenderId: '581579660522',
    projectId: 'kaamsetu-1d79f',
    storageBucket: 'kaamsetu-1d79f.firebasestorage.app',
    iosBundleId: 'com.kaamsetu.kaamsetu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBF4dAoa8REnub0K-_5lKzSjmHci15ckG0',
    appId: '1:581579660522:web:bf0fd10c3e0f670fc4cb93',
    messagingSenderId: '581579660522',
    projectId: 'kaamsetu-1d79f',
    authDomain: 'kaamsetu-1d79f.firebaseapp.com',
    storageBucket: 'kaamsetu-1d79f.firebasestorage.app',
    measurementId: 'G-33BZYBK3EF',
  );
}
